# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Currency-Convert-XE
version:      0.05
version_from: lib/Finance/Currency/Convert/XE.pm
installdirs:  site
requires:
    HTML::TokeParser:              0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
